import React from 'react';
import LineChartComponent from '../Components/Linechart';
import BarChartComponent from '../Components/BarChart';
import './HomePage.css';
import AnimalDeathRate from '../Components/AnimalDeathRate';
import { Container, Row, Col } from 'react-bootstrap';

function HomePage() {
  return (
    <div className="homepage">

        <div className="section row">
            <h2>What is poaching?</h2>

            <div className="col-12">

            <img src="./images/poaching.avif" class="img-fluid float-md-end mb-3 ms-md-3 col-md-4" alt="..." style={{ height: '230px', objectFit: 'cover' }}></img>
            <p>According to the International Fund for Animal Welfare-IFAW- poaching is the illegal hunting or capture of animals that are not one’s own. 
                In many cases, poaching involves killing animals with the intent to acquire their meat, horns, scales, or other body parts. In other cases, 
                poaching involves the live capture of animals, which are then trafficked for the illegal exotic pet trade, for use in entertainment or tourism, 
                and for other exploitative purposes such as the extraction of bile from bears. </p>
            </div>
      </div>
      
      {/* Animal death count section */}
      <div class="row ">
      <div className="d-flex align-items-center col-6 p-4 shadow rounded bg-white" style={{marginBottom:'25px', marginRight:'20px'}}>
        <div className="display-number text-center">
          <div style={{ fontSize: '36px', fontWeight: 'bold', color: '#d9534f' }}>
            30 000
          </div>
        </div>
        <div className="ms-4">
          <p className="mb-0 text-muted" style={{ fontSize: '14px', maxWidth: '220px' }}>
            Species Are Driven to Extinction Annually (Center for Biological Diversity)
          </p>
        </div>
      </div>
      {/* Money section */}
      <div className="d-flex align-items-center col-5 p-4 shadow rounded bg-white" style={{marginBottom:'25px'}}>
        <div className="display-number text-center">
          <div style={{ fontSize: '36px', fontWeight: 'bold', color: '#d9534f' }}>
            $7 to $23 billion
          </div>
        </div>
        <div className="ms-4">
          <p className="mb-0 text-muted" style={{ fontSize: '14px', maxWidth: '220px' }}>
            is the turnover generated by poaching
          </p>
        </div>
      </div>
     </div>
      <Container fluid className="my-5">
      <Row className="g-3">
        {/* Left big card */}
        <Col md={6}>
           <AnimalDeathRate />
        </Col>

        {/* Right stacked small cards */}
        <Col md={6}>
          <Row className="g-3 shadow rounded bg-white">
           
              <LineChartComponent />
           
          </Row>
        </Col>
      </Row>
    </Container>
     


      

      {/* Another Section: Text or More Charts */}
      <div className="section">
        <h6>Insights</h6>
        <p>Charts show increasing engagement and revenue trends for Q1.</p>
      </div>
    </div>
  );
}

export default HomePage;
